### ISSUE TITLE
Contribution Discussion.

### ISSUE THREAD

**Issue by sdsubhajitdas** [sdsubhajitdas/Compiler-Design-Assignment#1]
Let everyone know what question you are working on so that others can avoid that question.
 - Please writing clean code with meaningful variable names.
 - Please add comments so that everyone understands what you are writing.
 - If creating a function then small documentation about each argument will be helpful.
 - If you cannot complete then let everyone know.

Please create your own branch and then generate a pull request to the master branch. Do not work on the master branch it might create problems during merging.
Also before pushing keep your repo updated.

[Check this for example.](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/blob/master/2.c)

Question name should be in this format.
< Question Number >.c
Eg: 1.c, 2.c, 30.c
And commit message should be "Question < Question Number > added."
Each commit should contain only one code.

**Comment by sdsubhajitdas** [comment]
I am currently working on Question 2 will push shortly.

**Comment by sdsubhajitdas** [comment]
Working on Question 3.

**Comment by bitan1998** [comment]
Question no 1 done

**Comment by sdsubhajitdas** [comment]
Working one Question?

**Comment by bitan1998** [comment]
Working on question no 15

**Comment by bitan1998** [comment]
Question no 15 done

**Comment by bitan1998** [comment]
Doing Question no 16

**Comment by sdsubhajitdas** [comment]
Doing Question 6

**Comment by sdsubhajitdas** [comment]
Doing Question 7

**Comment by bitan1998** [comment]
DOING QUESTION NO 19

**Comment by bitan1998** [comment]
Question no 23 done

**Comment by sdsubhajitdas** [comment]
Doing Question 9

**Comment by bitan1998** [comment]
Question no 29 done

**Comment by sdsubhajitdas** [comment]
Doing Question 11

**Comment by koushikmajumder97** [comment]
Question 13 done

**Comment by sdsubhajitdas** [comment]
Doing Question 12

**Comment by sdsubhajitdas** [comment]
@koushikmajumder97  Start pushing then. Thanks nibba <3

**Comment by koushikmajumder97** [comment]
Question No 35 done

**Comment by koushikmajumder97** [comment]
Currently doing Question no 38

**Comment by koushikmajumder97** [comment]
Question no 38 done

**Comment by tukykarmakar** [comment]
Question 14 Done.

**Comment by koushikmajumder97** [comment]
Doing question no 18..almost done

**Comment by tukykarmakar** [comment]
Doing 17

**Comment by koushikmajumder97** [comment]
Question 18 done

**Comment by tukykarmakar** [comment]
Question 17 needs improvement. The code detects all keywords and identifiers but cannot separate strings from them. Also, it cannot detect escape sequences ('\n', '\t', '\r', etc).
[17.txt](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/files/3863674/17.txt)

**Comment by tukykarmakar** [comment]
Question 34 done

**Comment by tukykarmakar** [comment]
Question 36 done

**Comment by tukykarmakar** [comment]
I have found some reference materials for the following questions.
[Question 22](https://www.coders-hub.com/2013/05/c-code-for-context-free-grammercfg.html)
Question 24: [1](https://www.geeksforgeeks.org/program-calculate-first-follow-sets-given-grammar/) [2](https://www.codingalpha.com/find-first-and-follow-grammar-c-program/) [3](https://karthikalapati.blogspot.com/2016/04/first-and-follow-of-given-grammar-using.html)
[Question 30](https://www.coders-hub.com/2013/05/c-code-for-regular-grammer.html)

These have a different version of the same objective mentioned in the pdf. They either have different formats of inputs/outputs or are implemented differently.

**Comment by tukykarmakar** [comment]
@sdsubhajitdas @bitan1998 @koushikmajumder97 @notsrijit
I have a proposition...
One of us can assemble all the codes and make the assignment file while another one makes a "help" file for the exams. What do you all say??
Those should be created by tomorrow (20/11/2019) evening for everyone to be able to use them without problem.

I have assembled the codes for AI and Image Processing for a "help" file below.
[ImageProcessingBreak.txt](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/files/3864452/ImageProcessingBreak.txt)
[PrologBreak.txt](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/files/3864454/PrologBreak.txt)

Here are the assignment files for them respectively
[AI_Assignments.docx](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/files/3864465/AI_Assignments.docx)
[ImageProcessingAssignment.pdf](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/files/3864466/ImageProcessingAssignment.pdf)

Good Luck Everyone!!

**Comment by notsrijit** [comment]
I'll be uploading the "helpful" txt file for compiler design.

**Comment by sdsubhajitdas** [comment]
Nice work guys proud of everyone

**Comment by notsrijit** [comment]
[CompilerDesign.txt](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/files/3867941/CompilerDesign.txt)

**Comment by tukykarmakar** [comment]
[CompilerDesignAssignments.docx](https://github.com/sdsubhajitdas/Compiler-Design-Assignment/files/3869569/CompilerDesignAssignments.docx)

**Comment by sdsubhajitdas** [comment]
My Nibbas thanks i am closing this issue. ❤️
